import { Montserrat, Lalezar } from "next/font/google";

import "./globals.css";
import Navbar from "./components/Nav/navbar";
import Footer from "./components/footer/footer";

const fontBoddy = Montserrat({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"] ,
                weight:['400']});

export const metadata = {
  title: "E-commerce ITCA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={fontBoddy.className}>
      <div className="container">
      <Navbar/>
      
      
      
      {children}
      
      <Footer/>
      </div>
      </body>
    </html>
  );
}
